### ISSUE TITLE
dist/web/entry.js 404错误

### ISSUE THREAD

**Issue by winyluo** [osmartian/weex-frame#23]
麻烦大神解答一下，使用npm run serve 执行后，页面不出来，显示dist/web/entry.js 404 ，是什么问题

**Comment by walid1992** [comment]
npm run dev 也要执行，可以执行./start脚本

**Comment by uneverno** [comment]
android studio 运行的时候总是报错Network Error,请问如何解决？

**Comment by walid1992** [comment]
执行下 npm run init 这个指令是写入IP的，可能IP地址不对

**Comment by ccvcd** [comment]
默认应用是通过网络请求js文件的，你需要打开npm run server服务，或者你修改
platforms\android\app\src\main\res\xml\app_config.xml文件中的launch_locally项值，设置成true,从本地读取就可以了。
